---
- hosts: localhost
  become: no
  gather_facts: no
  #vars_files: 
  #  - sf_role/vars/createPackage.yml # use it for custom vars files, only vars/main.yml is automatically imported
  roles:
    - sf_role
    - sf_mods
  tasks:
    - name: test role
      debug: msg="testing"

    - debug:  
        msg: "Example variable import: {{ packageType }}"

    - name: Execute Sample Task
      ansible.builtin.include_tasks:
        createPackage.yml

